## 27 - 8 - 26

## Array Creation function


In [2]:
import numpy as np

In [3]:
a= np.array([1,2,3])
print("Array a:", a)

Array a: [1 2 3]


In [4]:
b= np.arange(0,10,3)
print("Array b:\n", b)

Array b:
 [0 3 6 9]


In [5]:
d= np.zeros((2,3))
print("Array d:\n", d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
d= np.zeros((2,3), dtype=int)
print("Array d:\n", d)

Array d:
 [[0 0 0]
 [0 0 0]]


In [7]:
e= np.ones((3,2))
print("Array e:\n", e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
# create an identity matrix

f= np.eye(4)  # all digonals are 1
print("Identity Mtrix f:\n", f)

Identity Mtrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Array Manipulation Function

In [9]:
# Reshape an array

a1= np.array([1,2,3])
reshaped= np.reshape(a1,(1,3))
print("Reshaped Array:\n" , reshaped)

Reshaped Array:
 [[1 2 3]]


In [10]:
a1= np.array([1,2,3])
reshaped= np.reshape(a1,(3,1))
print("Reshaped Array:\n" , reshaped)

Reshaped Array:
 [[1]
 [2]
 [3]]


In [11]:
# Flatten an array 

f1 = np. array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattend=np.ravel(f1)
print("flattend array:\n", flattend)

flattend array:
 [ 1  2  3  4  5  6  7  8  9 10]


In [12]:
# Transpose an array --> convert rows to columns and columns to rows

e1 = np. array([[1,2],[3,4]])
transposed=np.transpose(e1)
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [13]:
# Stack arrays vertically

a2= np.array([1,2])
b2=np.array([3,4])
stacked= np.vstack([a2,b2])
print("stacked arrays:\n", stacked)

stacked arrays:
 [[1 2]
 [3 4]]


In [14]:
# Stack arrays horizontal

a2= np.array([1,2])
b2=np.array([3,4])
stacked= np.hstack([a2,b2])
print("stacked arrays:\n", stacked)

stacked arrays:
 [1 2 3 4]


## Math operations

In [15]:
# Add 2 array

g = np.array([1,2,3,4])
added= np.add(g,2) # Add 2 to each element
print("Added 2 to g:", added)

Added 2 to g: [3 4 5 6]


In [16]:
# square each element

squared= np.power(g,2)

print("squared g:", squared)

squared g: [ 1  4  9 16]


In [17]:
# square root each element

sqrtt_val= np.sqrt(g)

print("square root of g:", sqrtt_val)

square root of g: [1.         1.41421356 1.73205081 2.        ]


In [18]:
print(a)
print(g)

[1 2 3]
[1 2 3 4]


In [19]:
# Dot product --> both the variable have same number of items

a3 = np.array([1,2,3])
dot_product= np.dot(a,g)
print("Dot product of a and g :", dot_product)  #Dimensions are not same so error

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [20]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [21]:
a3 = np.array([1,2,3])
dot_product= np.dot(a1,a)
print("Dot product of a1 and a:", dot_product) 

Dot product of a1 and a: 14


## Statistical functions

In [22]:
#mean

s= np.array([1,2,3,4])
mean= np.mean(s)
print("Mean of s:", mean)

Mean of s: 2.5


In [23]:
# variance of an array

var= np.var(s)
print("variance of s is:", var)


variance of s is: 1.25


In [24]:
# standard deviation of an array

std_dev= np. std(s)
print("standard deviation of s is:", std_dev)

standard deviation of s is: 1.118033988749895


In [25]:
#Minimum element of an array

minimum = np.min(s)
print("min of s:", minimum)

min of s: 1


In [26]:
#maximum element of an array

maximum = np.max(s)
print("max of s:", maximum)

max of s: 4


## Linear algebra

In [28]:
# Create a matrix
matrix = np.array([[1, 2], [3, 4]]) 
matrix

array([[1, 2],
       [3, 4]])

## Random Sampling Function

In [29]:
# Generate random values between 0 and 1

random_vals= np.random.rand(3) # Array of 3 random values btw 0 and 1
print("Random values:", random_vals)

Random values: [0.25959692 0.77505564 0.91949274]


In [30]:
# generate random integer

rand_ints= np.random.randint(0, 10, size=5) #  random int btw 0 and 1
print("Random integers:", rand_ints)

Random integers: [4 8 2 9 4]


In [31]:
# set seed for reproductibility ---> once the integer generated it won't change in seed

np.random.seed(1)

 #generate random integers
rand_ints= np.random.randint(0, 10, size=5) #  random int btw 0 and 1
print("Random integers:", rand_ints)

Random integers: [5 8 9 5 0]


## Boolean & Logical Functions

In [32]:
# Check if all elements are True

# all
logical_test = np.array([True, False, True]) 
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [33]:
# Check if all elements are True
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [34]:
# Check if all elements are True
logical_test = np.array([False, True, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [35]:
# Check if any elements are True
# any
any_true = np.any(logical_test)  # Check if any are True
print("Any elements True:", any_true)

Any elements True: True


## Set Operations

In [36]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [37]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


## Array Attribute Functions

In [38]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)


Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


## Other Functions

In [39]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [40]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 24


In [41]:
#Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
