In [1]:
import numpy as np 

In [2]:
import sys 
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

## Creating List

In [3]:
my_list = [0,1,2,3,4,5]
my_list 

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

## Converting List to Array

In [5]:
arr = np.array(my_list) 

In [6]:
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(my_list)

list

## Range

In [8]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(9) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
np.arange(0, 5) 

array([0, 1, 2, 3, 4])

In [11]:
np.arange(10,20) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int64)

In [13]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [14]:
np.arange(-16,10) 

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [15]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [16]:
np.arange(30,20)  # 1st arg always be < then 2nd arg

array([], dtype=int64)

In [17]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [18]:
np.arange(10,10) 

array([], dtype=int64)

In [19]:
np.arange(10,30,5)  # 10- starting from 30- end point 5 - step count

array([10, 15, 20, 25])

In [20]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [21]:
range(5)

range(0, 5)

In [22]:
r= range(5)
r

range(0, 5)

In [23]:
for i in r:
    print(i)

0
1
2
3
4


In [24]:
list(range(5))

[0, 1, 2, 3, 4]

In [25]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
list(range(1,10,3))

[1, 4, 7]

In [27]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

## Zeros

In [28]:
np.zeros(10) # bydefault it is float , PARAMETER TUNING--> what is sytem given automatically 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np . zeros (5 , dtype=int) #converted float to int ,  this is called  HYPERPARAMETER TUNING --> if user change the system parameter.

array([0, 0, 0, 0, 0])

In [30]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [31]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [32]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [34]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [36]:
np.zeros((10,30), dtype=  int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [37]:
np.zeros((10,10),dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# Bydefaul 1arge -- will give row & 2nd arg - columns

In [38]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
n1 = (6,8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [40]:
n= (6,7)
print(np.zeros(n))


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## Ones

In [41]:
np.ones(3)

array([1., 1., 1.])

In [42]:
np.ones((3,3)) # PARAMETER TUNING

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
np.ones(4, dtype=int) # HYPERPARAMETER TUNING

array([1, 1, 1, 1])

In [44]:
np.ones(4)

array([1., 1., 1., 1.])

In [45]:
n

(6, 7)

In [46]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [47]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [48]:
np.two((2,3)) 

AttributeError: module 'numpy' has no attribute 'two'

In [50]:
np.three((2,3)) 

AttributeError: module 'numpy' has no attribute 'three'

In [51]:
np.ones(2)

array([1., 1.])

In [52]:
np.ones((2,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
np.ones((6,10),dtype = int) 

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

## rand and randint

In [54]:
np . random . rand(2) # it will generate only float value

array([0.12141112, 0.63430593])

In [55]:
np.random.rand(3,5)

array([[0.7734936 , 0.29530011, 0.73131327, 0.35080122, 0.79512188],
       [0.98300827, 0.41461164, 0.18954246, 0.55874101, 0.33353981],
       [0.49704156, 0.75407893, 0.48813108, 0.65959644, 0.71896094]])

In [56]:
np.random.rand(3)

array([0.31200816, 0.65677076, 0.19297194])

In [57]:
np . random . randint(2) # it will generate random integer between 0 and n-1

0

In [58]:
np.random.randint(4,6)

4

In [59]:
np . random . randint(2,9) # it will show values between (2-(9-1))

4

In [60]:
np.random.randint(2,20,4) # generate 4 random integer between 2-20

array([14,  3,  8, 11], dtype=int32)

In [61]:
np.random.randint(0,1) 

0

In [62]:
np.random.randint(10,20,5) # generate 5 random integer between 10-20

array([14, 16, 11, 17, 15], dtype=int32)

In [63]:
np.random.randint(1,6,4)

array([1, 3, 3, 3], dtype=int32)

In [64]:
np.random.randint(1)   # generates one radom integer from 0 up to (but not including) 1

0

In [65]:
np.random.randint(30,20,10) 

ValueError: low >= high

In [66]:
np.random.randint(-30,20,10) 

array([ 18,  -4,   9,  17,  -5,  18, -29,  11, -20, -27], dtype=int32)

In [67]:
np.random.randint(20,30,10) 

array([21, 20, 25, 20, 28, 28, 24, 20, 22, 21], dtype=int32)

In [68]:
np.random.randint(5,9)

6

In [69]:
np.random.randint(10,21,3)

array([13, 13, 17], dtype=int32)

In [70]:
np.random.randint(1,12,10)

array([11,  2,  4,  8,  7,  9,  4,  1, 10,  6], dtype=int32)

In [71]:
np.random.randint(10,40,(10,10)) # creates a 10 × 10 matrix (array) filled with random integers from 10 to 39.

array([[16, 16, 23, 31, 24, 25, 20, 36, 39, 39],
       [15, 21, 28, 27, 11, 14, 31, 21, 34, 29],
       [16, 32, 26, 38, 27, 10, 23, 38, 18, 37],
       [31, 15, 38, 13, 33, 35, 24, 22, 11, 23],
       [17, 17, 28, 17, 14, 30, 35, 21, 13, 22],
       [12, 25, 32, 39, 15, 12, 14, 33, 15, 31],
       [22, 20, 21, 13, 33, 17, 13, 27, 16, 11],
       [12, 24, 17, 19, 29, 30, 39, 36, 23, 23],
       [36, 18, 15, 12, 30, 25, 36, 11, 14, 32],
       [18, 22, 20, 11, 17, 13, 16, 25, 17, 18]], dtype=int32)

In [72]:
np.random.randint(1,100,(12,12))

array([[91, 73, 34, 69, 56, 40, 63, 54, 65, 39, 11, 84],
       [62,  3, 99, 36, 31, 27, 78, 12, 77, 29, 75, 63],
       [53, 38, 21, 66, 50, 35, 42, 90, 35, 34, 64, 66],
       [77, 22, 71, 89, 45, 65, 74, 66, 47, 70, 18, 10],
       [70, 98, 39, 83, 24, 95,  9, 15, 97, 15, 41, 54],
       [45, 55, 55, 35, 31, 46, 49, 41, 67, 51, 79,  7],
       [ 5, 81, 16, 88, 36, 53, 56, 21, 32,  2, 15, 74],
       [76, 12,  4, 28, 67, 48, 96, 86, 84, 59, 98, 47],
       [80, 75, 99, 86, 80, 61, 35, 52, 16, 40, 92, 57],
       [36, 52, 94, 77, 28, 45, 28, 78, 71, 66, 26, 73],
       [45,  6, 28, 45, 33, 94, 12, 45,  1,  5, 79, 83],
       [26, 34, 85, 54, 31, 41, 74, 13, 94, 29, 22, 61]], dtype=int32)

## reshape

In [73]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [75]:
np.arange(1,13).reshape(5,4) # less elements to forn matrix

ValueError: cannot reshape array of size 12 into shape (5,4)

In [76]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [77]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [132]:
b1 = np.random.randint(5,10,(2,3))
b1

array([[6, 7, 9],
       [9, 8, 6]], dtype=int32)

In [133]:
b1 . reshape(6,1)

array([[6],
       [7],
       [9],
       [9],
       [8],
       [6]], dtype=int32)

In [135]:
b1 . reshape(1,6)

array([[6, 7, 9, 9, 8, 6]], dtype=int32)

In [136]:
b1 . reshape(3,2)

array([[6, 7],
       [9, 9],
       [8, 6]], dtype=int32)

In [142]:
b1 . reshape(2,3 , order='C') # C means C-style / row-major order --> NumPy takes elements row by row

array([[6, 7, 9],
       [9, 8, 6]], dtype=int32)

In [140]:
arr.reshape(2,3,order='F')  #F means Fortran-style ordering --> NumPy fills the new array column by column:

array([[0, 2, 4],
       [1, 3, 5]])

In [141]:
arr.reshape(2,3,order='A') # A means "Any" --> 
                           # Use Fortran order if the array is already stored in Fortran-contiguous memory; otherwise use C order.
                          # For a normal NumPy array, you'll usually get behavior like C
                        
                        

array([[0, 1, 2],
       [3, 4, 5]])

In [143]:
import numpy as np

# creating a Numpy array
num_array = np.arange(100).reshape(20, 5)
print(num_array)

# Display array in Fortran order 

print("\n  C type array:")
for num_array in np.nditer(num_array, order="C"):
	print(num_array,end=' ')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]

  C type array:
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

In [146]:
import numpy as np

# creating a Numpy array
num_array = np.arange(100).reshape(20, 5)
print(num_array)

# Display array in Fortran order 

print("\n  F type array:")
for num_array in np.nditer(num_array, order="F"):
	print(num_array,end=' ')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]

  F type array:
0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 1 6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96 2 7 12 17 22 27 32 37 42 47 52 57 62 67 72 77 82 87 92 97 3 8 13 18 23 28 33 38 43 48 53 58 63 68 73 78 83 88 93 98 4 9 14 19 24 29 34 39 44 49 54 59 64 69 74 79 84 89 94 99 

## slicing in matrix

In [79]:
b = np.random.randint(10,20,(5,4))
b

array([[15, 12, 10, 19],
       [17, 15, 13, 18],
       [16, 17, 19, 17],
       [17, 19, 11, 12],
       [19, 12, 17, 14]], dtype=int32)

In [80]:
type(b)

numpy.ndarray

In [81]:
b

array([[15, 12, 10, 19],
       [17, 15, 13, 18],
       [16, 17, 19, 17],
       [17, 19, 11, 12],
       [19, 12, 17, 14]], dtype=int32)

In [82]:
b[:]

array([[15, 12, 10, 19],
       [17, 15, 13, 18],
       [16, 17, 19, 17],
       [17, 19, 11, 12],
       [19, 12, 17, 14]], dtype=int32)

In [83]:
b[1:3]

array([[17, 15, 13, 18],
       [16, 17, 19, 17]], dtype=int32)

In [84]:
b[1:2]

array([[17, 15, 13, 18]], dtype=int32)

In [85]:
b[0:-2]

array([[15, 12, 10, 19],
       [17, 15, 13, 18],
       [16, 17, 19, 17]], dtype=int32)

In [86]:
b

array([[15, 12, 10, 19],
       [17, 15, 13, 18],
       [16, 17, 19, 17],
       [17, 19, 11, 12],
       [19, 12, 17, 14]], dtype=int32)

In [87]:
b[1,-1]

np.int32(18)

In [88]:
b[1,3]

np.int32(18)

In [89]:
b[0,2]

np.int32(10)

In [90]:
b[-5,3]

np.int32(19)

In [91]:
b[-5,-3]

np.int32(12)

In [92]:
b[-4,2]

np.int32(13)

In [93]:
np.random.randint(10,20,(5,5))

array([[11, 18, 14, 19, 14],
       [13, 12, 18, 17, 12],
       [18, 17, 10, 15, 15],
       [15, 16, 10, 19, 15],
       [15, 13, 12, 16, 11]], dtype=int32)

In [94]:
b

array([[15, 12, 10, 19],
       [17, 15, 13, 18],
       [16, 17, 19, 17],
       [17, 19, 11, 12],
       [19, 12, 17, 14]], dtype=int32)

In [95]:
b[-4,-2]

np.int32(13)

In [96]:
a = np.random.randint(10,20,10)
a

array([18, 19, 18, 15, 13, 16, 15, 13, 16, 18], dtype=int32)

In [97]:
id(a)

2194135603152

In [98]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[ 4, 99, 99, 88, 29, 57, 32, 10, 37, 71],
       [ 6, 73,  0,  4, 58, 45, 41, 82, 73, 59],
       [89, 90, 48, 79, 96, 86, 82,  8, 91, 55],
       [ 3,  5, 49, 24, 11, 80, 99, 37, 95, 27],
       [65, 63, 39, 93, 63, 90,  3, 94,  4, 28],
       [78, 65,  3, 81,  1,  0, 14, 72, 47, 99],
       [ 7, 88, 73, 75, 70, 35, 43, 38, 83,  5],
       [88,  8, 56, 57, 77, 14, 46,  2, 58, 45],
       [94,  5, 11, 11, 25, 61, 89, 99, 83, 10],
       [88, 76, 94, 23, 28, 64, 45, 46, 49, 13]], dtype=int32)

In [99]:
arr2[:]

array([[ 4, 99, 99, 88, 29, 57, 32, 10, 37, 71],
       [ 6, 73,  0,  4, 58, 45, 41, 82, 73, 59],
       [89, 90, 48, 79, 96, 86, 82,  8, 91, 55],
       [ 3,  5, 49, 24, 11, 80, 99, 37, 95, 27],
       [65, 63, 39, 93, 63, 90,  3, 94,  4, 28],
       [78, 65,  3, 81,  1,  0, 14, 72, 47, 99],
       [ 7, 88, 73, 75, 70, 35, 43, 38, 83,  5],
       [88,  8, 56, 57, 77, 14, 46,  2, 58, 45],
       [94,  5, 11, 11, 25, 61, 89, 99, 83, 10],
       [88, 76, 94, 23, 28, 64, 45, 46, 49, 13]], dtype=int32)

In [100]:
arr2[0:5]

array([[ 4, 99, 99, 88, 29, 57, 32, 10, 37, 71],
       [ 6, 73,  0,  4, 58, 45, 41, 82, 73, 59],
       [89, 90, 48, 79, 96, 86, 82,  8, 91, 55],
       [ 3,  5, 49, 24, 11, 80, 99, 37, 95, 27],
       [65, 63, 39, 93, 63, 90,  3, 94,  4, 28]], dtype=int32)

In [101]:
arr2[1,4] 

np.int32(58)

In [102]:
arr2[-5,5] 

np.int32(0)

In [103]:
arr2[-5,-5]

np.int32(0)

In [104]:
arr2[-1,-2]

np.int32(49)

In [105]:
arr2

array([[ 4, 99, 99, 88, 29, 57, 32, 10, 37, 71],
       [ 6, 73,  0,  4, 58, 45, 41, 82, 73, 59],
       [89, 90, 48, 79, 96, 86, 82,  8, 91, 55],
       [ 3,  5, 49, 24, 11, 80, 99, 37, 95, 27],
       [65, 63, 39, 93, 63, 90,  3, 94,  4, 28],
       [78, 65,  3, 81,  1,  0, 14, 72, 47, 99],
       [ 7, 88, 73, 75, 70, 35, 43, 38, 83,  5],
       [88,  8, 56, 57, 77, 14, 46,  2, 58, 45],
       [94,  5, 11, 11, 25, 61, 89, 99, 83, 10],
       [88, 76, 94, 23, 28, 64, 45, 46, 49, 13]], dtype=int32)

In [106]:
arr2[::-1]

array([[88, 76, 94, 23, 28, 64, 45, 46, 49, 13],
       [94,  5, 11, 11, 25, 61, 89, 99, 83, 10],
       [88,  8, 56, 57, 77, 14, 46,  2, 58, 45],
       [ 7, 88, 73, 75, 70, 35, 43, 38, 83,  5],
       [78, 65,  3, 81,  1,  0, 14, 72, 47, 99],
       [65, 63, 39, 93, 63, 90,  3, 94,  4, 28],
       [ 3,  5, 49, 24, 11, 80, 99, 37, 95, 27],
       [89, 90, 48, 79, 96, 86, 82,  8, 91, 55],
       [ 6, 73,  0,  4, 58, 45, 41, 82, 73, 59],
       [ 4, 99, 99, 88, 29, 57, 32, 10, 37, 71]], dtype=int32)

In [107]:
arr2[::-2]

array([[88, 76, 94, 23, 28, 64, 45, 46, 49, 13],
       [88,  8, 56, 57, 77, 14, 46,  2, 58, 45],
       [78, 65,  3, 81,  1,  0, 14, 72, 47, 99],
       [ 3,  5, 49, 24, 11, 80, 99, 37, 95, 27],
       [ 6, 73,  0,  4, 58, 45, 41, 82, 73, 59]], dtype=int32)

In [108]:
arr2[::-3]

array([[88, 76, 94, 23, 28, 64, 45, 46, 49, 13],
       [ 7, 88, 73, 75, 70, 35, 43, 38, 83,  5],
       [ 3,  5, 49, 24, 11, 80, 99, 37, 95, 27],
       [ 4, 99, 99, 88, 29, 57, 32, 10, 37, 71]], dtype=int32)

In [109]:
arr2[0:10:3] #arr2[start : stop : step]

array([[ 4, 99, 99, 88, 29, 57, 32, 10, 37, 71],
       [ 3,  5, 49, 24, 11, 80, 99, 37, 95, 27],
       [ 7, 88, 73, 75, 70, 35, 43, 38, 83,  5],
       [88, 76, 94, 23, 28, 64, 45, 46, 49, 13]], dtype=int32)

In [110]:
arr2

array([[ 4, 99, 99, 88, 29, 57, 32, 10, 37, 71],
       [ 6, 73,  0,  4, 58, 45, 41, 82, 73, 59],
       [89, 90, 48, 79, 96, 86, 82,  8, 91, 55],
       [ 3,  5, 49, 24, 11, 80, 99, 37, 95, 27],
       [65, 63, 39, 93, 63, 90,  3, 94,  4, 28],
       [78, 65,  3, 81,  1,  0, 14, 72, 47, 99],
       [ 7, 88, 73, 75, 70, 35, 43, 38, 83,  5],
       [88,  8, 56, 57, 77, 14, 46,  2, 58, 45],
       [94,  5, 11, 11, 25, 61, 89, 99, 83, 10],
       [88, 76, 94, 23, 28, 64, 45, 46, 49, 13]], dtype=int32)

In [111]:
arr2[:3]

array([[ 4, 99, 99, 88, 29, 57, 32, 10, 37, 71],
       [ 6, 73,  0,  4, 58, 45, 41, 82, 73, 59],
       [89, 90, 48, 79, 96, 86, 82,  8, 91, 55]], dtype=int32)

In [112]:
arr2

array([[ 4, 99, 99, 88, 29, 57, 32, 10, 37, 71],
       [ 6, 73,  0,  4, 58, 45, 41, 82, 73, 59],
       [89, 90, 48, 79, 96, 86, 82,  8, 91, 55],
       [ 3,  5, 49, 24, 11, 80, 99, 37, 95, 27],
       [65, 63, 39, 93, 63, 90,  3, 94,  4, 28],
       [78, 65,  3, 81,  1,  0, 14, 72, 47, 99],
       [ 7, 88, 73, 75, 70, 35, 43, 38, 83,  5],
       [88,  8, 56, 57, 77, 14, 46,  2, 58, 45],
       [94,  5, 11, 11, 25, 61, 89, 99, 83, 10],
       [88, 76, 94, 23, 28, 64, 45, 46, 49, 13]], dtype=int32)

In [113]:
arr2.max()

np.int32(99)

In [114]:
arr2.min()

np.int32(0)

In [115]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [116]:
from numpy import * 
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

In [117]:
from numpy import * # 256 function called internally
a = array([1,2,3,4,9])
mean(a)

np.float64(3.8)

## Indexing 

In [147]:
mat = np.arange(0,100).reshape(10,10) 

In [148]:
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [150]:
row = 4
col = 5

In [151]:
mat[row,col] 

np.int64(45)

In [152]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [153]:
mat[7]

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [154]:
mat[:,col] 

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [155]:
mat[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [156]:
mat[row,:] 

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [157]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [158]:
mat[:col] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [159]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [160]:
mat[:,8] 

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [161]:
mat[:,-1] 

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [162]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [163]:
mat[1,4]

np.int64(14)

In [165]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

# Masking

In [166]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [167]:
id(mat)

2194137363344

In [168]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [169]:
mat[mat==50] 

array([50])

In [170]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [171]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [172]:
a3 = mat[mat<=50] 
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [173]:
a4 = mat[mat==50]
a4

array([50])

## program for otp generation

In [175]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 0333


In [179]:
# another code

import random

digits = "0123456789"

otp = ""

for i in range(6):
    otp = otp + random.choice(digits)

print("Your OTP is:", otp)

Your OTP is: 657185
