In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.2'

## create list

In [3]:
my_list=[0, 1, 2 , 3, 4, 5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

## how to convert to array

In [5]:
arr = np . array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [10]:
np.arange(5,100,10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [11]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int64)

In [12]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [13]:
np.arange(-20.6,10)

array([-20.6, -19.6, -18.6, -17.6, -16.6, -15.6, -14.6, -13.6, -12.6,
       -11.6, -10.6,  -9.6,  -8.6,  -7.6,  -6.6,  -5.6,  -4.6,  -3.6,
        -2.6,  -1.6,  -0.6,   0.4,   1.4,   2.4,   3.4,   4.4,   5.4,
         6.4,   7.4,   8.4,   9.4])

## 26-08-26

In [14]:
np . zeros(5) #1-d arrays , bydefault it is float , this is called  PARAMETER TUNING--> what is sytem given automatically 

array([0., 0., 0., 0., 0.])

In [15]:
np . zeros (5 , dtype=int) #converted float to int ,  this is called  HYPERPARAMETER TUNING --> if user change the system parameter.

array([0, 0, 0, 0, 0])

In [16]:
np . zeros((2,2)) #PARAMETER (Float)

array([[0., 0.],
       [0., 0.]])

In [17]:
np . zeros((2,3), dtype=int) #HYPER PARAMETER (Float-->int)

array([[0, 0, 0],
       [0, 0, 0]])

In [18]:
np .zeros((10,3), dtype=int) # 10--> row , 3--> column

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [19]:
np .zeros((10,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [20]:
np . ones(4)

array([1., 1., 1., 1.])

In [21]:
np . ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [22]:
np.two(3)

AttributeError: module 'numpy' has no attribute 'two'

In [23]:
np.full((2, 3), 3, dtype=int)

array([[3, 3, 3],
       [3, 3, 3]])

In [24]:
np.full((2, 3), 2, dtype=int)

array([[2, 2, 2],
       [2, 2, 2]])

## otp

In [25]:
np . random . rand(2) # it will generate only float value

array([0.78567843, 0.44535656])

In [26]:
np . random . rand(4)

array([0.12523069, 0.30673043, 0.0114183 , 0.812648  ])

In [27]:
np . random . rand(2,3)

array([[0.9049556 , 0.04064183, 0.64175621],
       [0.90130509, 0.37828329, 0.17979458]])

In [28]:
np . random . randint(2) # it will generate random integer between 0 and n-1

0

In [29]:
np . random . randint(2,9) # it will show values between (2-(9-1))

7

In [30]:
np . random . randint(2,9, 4) #generate random integer between 2 to 9 of 4 element

array([4, 4, 8, 2], dtype=int32)

In [31]:
np. random. randint(10,40,(10,10))

# 10 * 10 matrix between 10 to 40

array([[15, 26, 22, 33, 35, 29, 12, 27, 33, 26],
       [36, 35, 10, 12, 11, 27, 34, 22, 38, 39],
       [24, 33, 15, 28, 33, 35, 29, 10, 19, 38],
       [31, 21, 28, 35, 34, 15, 11, 12, 30, 24],
       [28, 20, 22, 27, 27, 34, 23, 31, 18, 33],
       [17, 16, 25, 20, 20, 21, 19, 30, 39, 36],
       [17, 23, 18, 18, 14, 37, 18, 22, 16, 23],
       [38, 20, 21, 33, 30, 28, 12, 23, 26, 12],
       [29, 35, 29, 20, 29, 29, 19, 14, 36, 35],
       [19, 15, 31, 21, 28, 36, 32, 23, 38, 30]], dtype=int32)

In [32]:
arr1= np. random. randint(10,40,(10,10))  # here the dtype = int32 will be removed if we assign to a variable
print(arr1)

[[19 29 23 15 28 30 20 27 10 32]
 [20 12 11 16 38 16 12 25 11 27]
 [28 28 17 13 20 35 35 23 14 15]
 [26 11 36 33 37 11 32 14 34 18]
 [26 17 27 32 11 17 25 19 33 13]
 [38 14 23 15 25 24 31 24 15 20]
 [34 39 20 28 39 38 33 10 20 33]
 [30 21 24 14 17 12 38 36 17 34]
 [27 13 34 33 10 11 15 16 39 25]
 [27 35 13 38 35 20 27 36 19 19]]


In [33]:
arr1[5]

array([38, 14, 23, 15, 25, 24, 31, 24, 15, 20], dtype=int32)

In [53]:
arr2= np. random. randint(2,9,(5,7))  
print(arr2)

[[8 4 7 4 4 4 5]
 [4 3 6 6 7 5 6]
 [2 3 8 8 8 8 3]
 [6 8 5 5 4 6 4]
 [4 5 5 4 6 2 7]]


In [54]:
arr2[-3] # it will give specific row

array([2, 3, 8, 8, 8, 8, 3], dtype=int32)

In [55]:
arr2[2:10] # it will give value between indexex--> slicing

array([[2, 3, 8, 8, 8, 8, 3],
       [6, 8, 5, 5, 4, 6, 4],
       [4, 5, 5, 4, 6, 2, 7]], dtype=int32)

In [56]:
arr2[:] #entire matrix

array([[8, 4, 7, 4, 4, 4, 5],
       [4, 3, 6, 6, 7, 5, 6],
       [2, 3, 8, 8, 8, 8, 3],
       [6, 8, 5, 5, 4, 6, 4],
       [4, 5, 5, 4, 6, 2, 7]], dtype=int32)

In [57]:
arr2[: : -1] # reverse

array([[4, 5, 5, 4, 6, 2, 7],
       [6, 8, 5, 5, 4, 6, 4],
       [2, 3, 8, 8, 8, 8, 3],
       [4, 3, 6, 6, 7, 5, 6],
       [8, 4, 7, 4, 4, 4, 5]], dtype=int32)

In [58]:
arr2

array([[8, 4, 7, 4, 4, 4, 5],
       [4, 3, 6, 6, 7, 5, 6],
       [2, 3, 8, 8, 8, 8, 3],
       [6, 8, 5, 5, 4, 6, 4],
       [4, 5, 5, 4, 6, 2, 7]], dtype=int32)

In [59]:
arr2[: : 3] # here step value 3 print 0th index then count 3 then next 

array([[8, 4, 7, 4, 4, 4, 5],
       [6, 8, 5, 5, 4, 6, 4]], dtype=int32)

In [60]:
arr2

array([[8, 4, 7, 4, 4, 4, 5],
       [4, 3, 6, 6, 7, 5, 6],
       [2, 3, 8, 8, 8, 8, 3],
       [6, 8, 5, 5, 4, 6, 4],
       [4, 5, 5, 4, 6, 2, 7]], dtype=int32)

In [61]:
arr2[3,4] # print specific values from matrix

np.int32(4)

In [62]:
print(arr2[3,4] ) # here we use list[] because list are mutable we can't use tuple() it will give error because immutable.

4


In [63]:
arr2[-4,-5] 

np.int32(6)

In [64]:
arr2

array([[8, 4, 7, 4, 4, 4, 5],
       [4, 3, 6, 6, 7, 5, 6],
       [2, 3, 8, 8, 8, 8, 3],
       [6, 8, 5, 5, 4, 6, 4],
       [4, 5, 5, 4, 6, 2, 7]], dtype=int32)

In [67]:
arr2[0,1]=10  # changing specific value

In [68]:
arr2

array([[ 8, 10,  7,  4,  4,  4,  5],
       [ 4,  3,  6,  6,  7,  5,  6],
       [ 2,  3,  8,  8,  8,  8,  3],
       [ 6,  8,  5,  5,  4,  6,  4],
       [ 4,  5,  5,  4,  6,  2,  7]], dtype=int32)

In [70]:
arr2[ :,0] #print columns

array([8, 4, 2, 6, 4], dtype=int32)

In [71]:
arr2[ :,-3] 

array([4, 7, 8, 4, 6], dtype=int32)

In [72]:
arr2

array([[ 8, 10,  7,  4,  4,  4,  5],
       [ 4,  3,  6,  6,  7,  5,  6],
       [ 2,  3,  8,  8,  8,  8,  3],
       [ 6,  8,  5,  5,  4,  6,  4],
       [ 4,  5,  5,  4,  6,  2,  7]], dtype=int32)

In [73]:
arr2[2:5 , 2:5]  # [row , coluns]  print a specific part including rows and columns 

array([[8, 8, 8],
       [5, 5, 4],
       [5, 4, 6]], dtype=int32)

In [74]:
arr2[1:4 , 2:4]

array([[6, 6],
       [8, 8],
       [5, 5]], dtype=int32)

## Masking or filter in numpy

In [75]:
arr2

array([[ 8, 10,  7,  4,  4,  4,  5],
       [ 4,  3,  6,  6,  7,  5,  6],
       [ 2,  3,  8,  8,  8,  8,  3],
       [ 6,  8,  5,  5,  4,  6,  4],
       [ 4,  5,  5,  4,  6,  2,  7]], dtype=int32)

In [76]:
arr2 > 5 # print  True where value greater than 5 else false

array([[ True,  True,  True, False, False, False, False],
       [False, False,  True,  True,  True, False,  True],
       [False, False,  True,  True,  True,  True, False],
       [ True,  True, False, False, False,  True, False],
       [False, False, False, False,  True, False,  True]])

In [78]:
arr2[arr2 > 5] #to print specific value (filter in numpy)

array([ 8, 10,  7,  6,  6,  7,  6,  8,  8,  8,  8,  6,  8,  6,  6,  7],
      dtype=int32)

In [79]:
arr2[arr2 >= 5]

array([ 8, 10,  7,  5,  6,  6,  7,  5,  6,  8,  8,  8,  8,  6,  8,  5,  5,
        6,  5,  5,  6,  7], dtype=int32)

In [80]:
arr2[arr2 == 5]

array([5, 5, 5, 5, 5, 5], dtype=int32)

In [81]:
arr2[arr2 != 5]

array([ 8, 10,  7,  4,  4,  4,  4,  3,  6,  6,  7,  6,  2,  3,  8,  8,  8,
        8,  3,  6,  8,  4,  6,  4,  4,  4,  6,  2,  7], dtype=int32)

## Reshape

In [82]:
arr


array([0, 1, 2, 3, 4, 5])

In [83]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [84]:
arr.reshape(4,3) #doesn't have sufficient items

ValueError: cannot reshape array of size 6 into shape (4,3)

In [85]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [86]:
arr.reshape(1,6)


array([[0, 1, 2, 3, 4, 5]])

In [87]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [88]:
arr.max()

np.int64(5)

In [89]:
arr.min()

np.int64(0)